-- Data Understanding------------------------
SELECT * FROM supermart LIMIT 0;

--How many total records are in the dataset?
select count(row_id) as "Total_Records" from supermart;

--How many unique orders exist?
select count(distinct(order_id)) as "Total_Unique_Orders" from supermart;

--How many unique customers exist?
select count(distinct(customer_id)) as "Total_Customers" from supermart;

--How many unique products exist?
select count(distinct(product_id)) as "Total_Products" from supermart;

----Which columns contain NULL values?
SELECT
    COUNT(*) FILTER (WHERE order_id IS NULL) AS order_id_nulls,
    COUNT(*) FILTER (WHERE customer_id IS NULL) AS customer_id_nulls,
    COUNT(*) FILTER (WHERE sales IS NULL) AS sales_nulls,
    COUNT(*) FILTER (WHERE profit IS NULL) AS profit_nulls
FROM supermart;

--How many records belong to each segment?
select segment,count(segment) from supermart group by segment;

--How many records belong to each region?
select region,count(region) from supermart group by region;
--How many categories and sub-categories exist?
select count(distinct(category)) as "Total_Categories", count(distinct("sub-category")) as "Total_sub-categories" from supermart;

--What is the date range of the dataset?
select min(order_date) as "First_date", max(order_date) as "Last_Date" from supermart;

--Which city appears most frequently?
with city_counts as(
select city,count(*)as city_count
from supermart
group by city
)
select city,city_count
from city_counts 
where city_count=(
select max(city_count)
from city_counts
);

--Does one order contain multiple products?
SELECT order_id,
       COUNT(*)
FROM supermart
GROUP BY order_id
HAVING COUNT(*) > 1;

--How many loss-making transactions exist?
select count(*) from supermart where profit < 0;

--What discount range exists?
SELECT MIN(discount),MAX(discount),AVG(discount) FROM supermart;

--Are there a few huge orders skewing revenue?
SELECT MIN(sales),MAX(sales),AVG(sales) FROM supermart;

-- Sales Analysis---------------------------------------------------
--What is the total sales generated by the company?
select sum(sales) as "Total sales" from supermart;

--What is the average sales per order?
with avg_sales as(
select order_id, sum(sales) as sum_sales
from supermart
group by order_id
)
select avg(sum_sales) as Average_sales_per_order
from avg_sales;

--Which category generates the highest sales?
SELECT category,
       SUM(sales) AS total_sales
FROM supermart
GROUP BY category
ORDER BY total_sales DESC
LIMIT 1;

--Which sub-category generates the highest sales?
SELECT "sub-category",
       SUM(sales) AS total_sales
FROM supermart
GROUP BY "sub-category"
ORDER BY total_sales DESC
LIMIT 1;

--Which category generates the lowest sales?
SELECT category,
       SUM(sales) AS total_sales
FROM supermart
GROUP BY category
ORDER BY total_sales
LIMIT 1;

--Show sales contribution (%) by category.
with sale_percentage as(
select category, sum(sales) as "sum_sales" 
from supermart group by category 
)
select category, sum_sales, 
round( ( sum_sales * 100.0 / sum(sum_sales)over())::numeric, 2 ) as Percentage 
from sale_percentage 
order by Percentage desc;

--Show sales contribution (%) by sub-category.
with sale_percentage as(
select "sub-category",
sum(sales) as "sum_sales" 
from supermart
group by "sub-category"
)
select "sub-category",
sum_sales,
round(
(
sum_sales * 100.0 /
sum(sum_sales)over())::numeric,
2
) as Percentage
from sale_percentage
order by Percentage desc;

--Which 10 products generated the highest sales?
select product_name,p_sales
from product_sales
order by p_sales desc
limit 10;

--Which 10 products generated the lowest sales?

select product_name,p_sales
from product_sales
order by p_sales
limit 10;

--What are the top 10 cities by sales?
select city,c_sales
from city_sales
order by c_sales desc
limit 10;

-- profit analysis ------------------------------------------------------------

-- what is the total profit?

select round(sum(profit),2) as total_profit
from supermart;


-- which category generates the highest profit?

select category,
       sum(profit) as total_profit
from supermart
group by category
order by total_profit desc
limit 1;


-- which category generates the lowest profit?

select category,
       sum(profit) as total_profit
from supermart
group by category
order by total_profit
limit 1;


-- which sub-category generates the highest profit?

select "sub-category",
       sum(profit) as total_profit
from supermart
group by "sub-category"
order by total_profit desc
limit 1;


-- which sub-category generates the lowest profit?

select "sub-category",
       sum(profit) as total_profit
from supermart
group by "sub-category"
order by total_profit
limit 1;


-- which products generated losses?

select product_name,
       sum(profit) as total_profit
from supermart
group by product_name
having sum(profit) < 0
order by total_profit;


-- show the 10 biggest loss-making products

select product_name,
       sum(profit) as total_profit
from supermart
group by product_name
having sum(profit) < 0
order by total_profit
limit 10;


-- which states have negative overall profit?

select state,
       sum(profit) as total_profit
from supermart
group by state
having sum(profit) < 0
order by total_profit;


-- which cities have negative overall profit?

select city,
       sum(profit) as total_profit
from supermart
group by city
having sum(profit) < 0
order by total_profit;


-- calculate profit margin for each category

select category,
       round(
           (sum(profit) * 100.0 / sum(sales))::numeric,
           2
       ) as profit_margin
from supermart
group by category;



-- customer analysis ----------------------------------------------------------

-- who are the top 10 customers by sales?

select customer_name,
       sum(sales) as total_sales
from supermart
group by customer_name
order by total_sales desc
limit 10;


-- who are the top 10 customers by profit?

select customer_name,
       sum(profit) as total_profit
from supermart
group by customer_name
order by total_profit desc
limit 10;


-- which customers generated losses?

select customer_name,
       sum(profit) as total_profit
from supermart
group by customer_name
having sum(profit) < 0
order by total_profit;


-- which customer placed the highest number of orders?

select customer_name,
       count(distinct order_id) as total_orders
from supermart
group by customer_name
order by total_orders desc
limit 1;


-- which customer generated the highest average order value?

with customer_orders as(
select customer_name,
       order_id,
       sum(sales) as order_sales
from supermart
group by customer_name,order_id
)

select customer_name,
       avg(order_sales) as avg_order_value
from customer_orders
group by customer_name
order by avg_order_value desc
limit 1;


-- how many customers purchased only once?

with customer_orders as(
select customer_name,
       count(distinct order_id) as total_orders
from supermart
group by customer_name
)

select count(*)
from customer_orders
where total_orders = 1;


-- how many customers placed more than 5 orders?

with customer_orders as(
select customer_name,
       count(distinct order_id) as total_orders
from supermart
group by customer_name
)

select count(*)
from customer_orders
where total_orders > 5;


-- find the customer lifetime sales for every customer

select customer_name,
       round(sum(sales),2) as lifetime_sales
from supermart
group by customer_name
order by lifetime_sales desc;


-- find the customer lifetime profit for every customer

select customer_name,
       round(sum(profit),2) as lifetime_profit
from supermart
group by customer_name
order by lifetime_profit desc;


-- which segment contributes the most sales?

select segment,
       sum(sales) as total_sales
from supermart
group by segment
order by total_sales desc;



-- product analysis -----------------------------------------------------------

-- which category contains the most products?

select category,
       count(distinct product_name) as total_products
from supermart
group by category
order by total_products desc
limit 1;


-- which sub-category contains the most products?

select "sub-category",
       count(distinct product_name) as total_products
from supermart
group by "sub-category"
order by total_products desc
limit 1;


-- what is the average sales per product?

with product_sales as(
select product_name,
       sum(sales) as total_sales
from supermart
group by product_name
)

select avg(total_sales)
from product_sales;


-- which products sell frequently but generate low profit?

select product_name,
       count(*) as frequency,
       sum(profit) as total_profit
from supermart
group by product_name
having count(*) > 10
and sum(profit) < 100
order by frequency desc;


-- which products generate high sales but low profit margin?

select product_name,
       sum(sales) as total_sales,
       round(
         (sum(profit)*100.0/sum(sales))::numeric,
         2
       ) as profit_margin
from supermart
group by product_name
order by total_sales desc;


-- top selling product in each category

with product_sales as(
select category,
       product_name,
       sum(sales) as total_sales
from supermart
group by category,product_name
)

select *
from(
select *,
       rank() over(
       partition by category
       order by total_sales desc
       ) as rnk
from product_sales
)t
where rnk = 1;


-- most profitable product in each category

with product_profit as(
select category,
       product_name,
       sum(profit) as total_profit
from supermart
group by category,product_name
)

select *
from(
select *,
       rank() over(
       partition by category
       order by total_profit desc
       ) as rnk
from product_profit
)t
where rnk = 1;


-- products sold only once

select product_name
from supermart
group by product_name
having count(*) = 1;


-- products with negative total profit

select product_name,
       sum(profit) as total_profit
from supermart
group by product_name
having sum(profit) < 0;


-- sub-category with highest average discount

select "sub-category",
       avg(discount) as avg_discount
from supermart
group by "sub-category"
order by avg_discount desc
limit 1;


-- phase 6 : discount analysis -----------------------------------------------

-- what is the average discount offered?

select round(avg(discount)::numeric,2) as avg_discount
from supermart;


-- which category receives the highest discount?

select category,
       round(avg(discount)::numeric,2) as avg_discount
from supermart
group by category
order by avg_discount desc
limit 1;


-- which sub-category receives the highest discount?

select "sub-category",
       round(avg(discount)::numeric,2) as avg_discount
from supermart
group by "sub-category"
order by avg_discount desc
limit 1;


-- compare average profit at different discount levels

select discount,
       round(avg(profit)::numeric,2) as avg_profit
from supermart
group by discount
order by discount;


-- does higher discount lead to lower profit?

select discount,
       round(avg(profit)::numeric,2) as avg_profit
from supermart
group by discount
order by discount;


-- find orders with discounts above 50%

select *
from supermart
where discount > 0.5;


-- which products are most heavily discounted?

select product_name,
       round(avg(discount)::numeric,2) as avg_discount
from supermart
group by product_name
order by avg_discount desc
limit 10;


-- which customers received the highest total discounts?

select customer_name,
       round(sum(discount)::numeric,2) as total_discount
from supermart
group by customer_name
order by total_discount desc
limit 10;


-- compare profit margin for discounted vs non-discounted orders

select
case
    when discount = 0 then 'no_discount'
    else 'discounted'
end as discount_type,

round(
(sum(profit) * 100.0 / sum(sales))::numeric,
2
) as profit_margin

from supermart
group by discount_type;


-- find loss-making orders where discount was applied

select *
from supermart
where profit < 0
and discount > 0;


-- phase 7 : time series analysis --------------------------------------------

-- calculate sales by year

select extract(year from order_date) as year,
       round(sum(sales)::numeric,2) as total_sales
from supermart
group by year
order by year;


-- calculate profit by year

select extract(year from order_date) as year,
       round(sum(profit)::numeric,2) as total_profit
from supermart
group by year
order by year;


-- calculate sales by month

select extract(month from order_date) as month,
       round(sum(sales)::numeric,2) as total_sales
from supermart
group by month
order by month;


-- calculate profit by month

select extract(month from order_date) as month,
       round(sum(profit)::numeric,2) as total_profit
from supermart
group by month
order by month;


-- which month had the highest sales?

select extract(month from order_date) as month,
       round(sum(sales)::numeric,2) as total_sales
from supermart
group by month
order by total_sales desc
limit 1;


-- which month had the lowest sales?

select extract(month from order_date) as month,
       round(sum(sales)::numeric,2) as total_sales
from supermart
group by month
order by total_sales
limit 1;


-- which month had the highest profit?

select extract(month from order_date) as month,
       round(sum(profit)::numeric,2) as total_profit
from supermart
group by month
order by total_profit desc
limit 1;


-- which month had the lowest profit?

select extract(month from order_date) as month,
       round(sum(profit)::numeric,2) as total_profit
from supermart
group by month
order by total_profit
limit 1;


-- year over year sales growth -----------------------------------------------

with yearly_sales as(
select extract(year from order_date) as year,
       sum(sales) as total_sales
from supermart
group by year
)

select year,
       total_sales,
       lag(total_sales) over(order by year) as previous_year_sales,

       round(
       (
       (total_sales - lag(total_sales) over(order by year))
       * 100.0
       /
       lag(total_sales) over(order by year)
       )::numeric,
       2
       ) as yoy_growth_pct

from yearly_sales
order by year;

-- month over month sales growth ---------------------------------------------

with monthly_sales as(
select date_trunc('month',order_date) as month,
       sum(sales) as total_sales
from supermart
group by month
)

select month,
       total_sales,

       lag(total_sales)
       over(order by month) as previous_month_sales,

       round(
       (
       (total_sales - lag(total_sales) over(order by month))
       *100.0
       /
       lag(total_sales) over(order by month)
       )::numeric,
       2
       ) as mom_growth_pct

from monthly_sales
order by month;


-- phase 8 : window functions ------------------------------------------------

-- rank customers by total sales

with customer_sales as(
select customer_name,
       sum(sales) as total_sales
from supermart
group by customer_name
)

select *,
       rank() over(order by total_sales desc) as sales_rank
from customer_sales;


-- dense rank customers by profit

with customer_profit as(
select customer_name,
       sum(profit) as total_profit
from supermart
group by customer_name
)

select *,
       dense_rank() over(order by total_profit desc) as profit_rank
from customer_profit;


-- rank products within each category

with product_sales as(
select category,
       product_name,
       sum(sales) as total_sales
from supermart
group by category,product_name
)

select *,
       rank() over(
       partition by category
       order by total_sales desc
       ) as category_rank
from product_sales;


-- top 3 products in every category

with product_sales as(
select category,
       product_name,
       sum(sales) as total_sales
from supermart
group by category,product_name
)

select *
from(
select *,
       rank() over(
       partition by category
       order by total_sales desc
       ) as rnk
from product_sales
)t
where rnk <= 3;


-- running total sales over time

select order_date,
       sales,

       sum(sales)
       over(
       order by order_date
       ) as running_total_sales

from supermart;


-- running total profit over time

select order_date,
       profit,

       sum(profit)
       over(
       order by order_date
       ) as running_total_profit

from supermart;


-- cumulative sales by customer

select customer_name,
       sales,

       sum(sales)
       over(
       partition by customer_name
       order by order_date
       ) as cumulative_sales

from supermart;


-- previous order sales using lag()

select customer_name,
       order_date,
       sales,

       lag(sales)
       over(
       partition by customer_name
       order by order_date
       ) as previous_order_sales

from supermart;


-- sales difference between current and previous month

with monthly_sales as(
select date_trunc('month',order_date) as month,
       sum(sales) as total_sales
from supermart
group by month
)

select month,
       total_sales,

       lag(total_sales)
       over(order by month) as previous_month_sales,

       total_sales -
       lag(total_sales)
       over(order by month) as sales_difference

from monthly_sales;


-- highest sales order in each region

with region_orders as(
select region,
       order_id,
       sum(sales) as total_sales
from supermart
group by region,order_id
)

select *
from(
select *,
       rank() over(
       partition by region
       order by total_sales desc
       ) as rnk
from region_orders
)t
where rnk = 1;


-- phase 9 : ctes and advanced analysis --------------------------------------

-- customers whose sales are above average

with customer_sales as(
select customer_name,
       sum(sales) as total_sales
from supermart
group by customer_name
)

select *
from customer_sales
where total_sales >
(
select avg(total_sales)
from customer_sales
);


-- products whose profit is below average

with product_profit as(
select product_name,
       sum(profit) as total_profit
from supermart
group by product_name
)

select *
from product_profit
where total_profit <
(
select avg(total_profit)
from product_profit
);


-- customer segmentation

with customer_sales as(
select customer_name,
       sum(sales) as total_sales
from supermart
group by customer_name
)

select customer_name,
       total_sales,

case
when total_sales >= 10000 then 'high value'
when total_sales >= 5000 then 'medium value'
else 'low value'
end as customer_segment

from customer_sales;


-- repeat customers

select customer_name,
       count(distinct order_id) as total_orders
from supermart
group by customer_name
having count(distinct order_id) > 1;


-- inactive customers in last year of data (2017)

select distinct customer_name
from supermart
group by customer_name
having max(order_date) < '2017-01-01';


-- products with negative total profit

select product_name,
       sum(profit) as total_profit
from supermart
group by product_name
having sum(profit) < 0
order by total_profit;


-- profitability report by region and category

select region,
       category,

       round(sum(sales)::numeric,2) as total_sales,

       round(sum(profit)::numeric,2) as total_profit,

       round(
       (sum(profit)*100.0/sum(sales))::numeric,
       2
       ) as profit_margin

from supermart
group by region,category
order by region,category;



-------------------------------------- Moving to Tableau ------------------------------------
CREATE OR REPLACE VIEW v_superstore_base AS
SELECT
    row_id,
    order_id,
    order_date,
    ship_date,
    customer_id,
    customer_name,
    segment,
    country,
    city,
    state,
    region,
    product_id,
    category,
    "sub-category" AS sub_category,
    product_name,
    sales,
    quantity,
    discount,
    profit
FROM supermart;




--------------------------------- FEATURE ENGINEERING ------------------------
CREATE OR REPLACE VIEW v_superstore_features AS
SELECT 
    b.*, -- Use the alias here to avoid the syntax error
    
    -- 1. Profit Margin
    ROUND((b.profit / NULLIF(b.sales, 0)) * 100, 2) AS profit_margin_pct,

    -- 2. Discount Impact Flag
    CASE 
        WHEN b.discount = 0 THEN 'No Discount'
        WHEN b.discount <= 0.2 THEN 'Low Discount'
        WHEN b.discount <= 0.5 THEN 'Medium Discount'
        ELSE 'High Discount'
    END AS discount_segment,

    -- 3. Order Year / Month
    EXTRACT(YEAR FROM b.order_date) AS order_year,
    EXTRACT(MONTH FROM b.order_date) AS order_month,

    -- 4. Shipping Delay (days)
    (b.ship_date - b.order_date) AS shipping_days,

    -- 5. Profit Category
    CASE
        WHEN b.profit < 0 THEN 'Loss'
        WHEN b.profit < 100 THEN 'Low Profit'
        WHEN b.profit < 500 THEN 'Medium Profit'
        ELSE 'High Profit'
    END AS profit_segment,

    -- 6. Sales Banding
    CASE
        WHEN b.sales < 100 THEN 'Low Value'
        WHEN b.sales < 500 THEN 'Medium Value'
        ELSE 'High Value'
    END AS sales_segment

FROM v_superstore_base b; -- 'b' acts as the alias for your base view

-------------------------------------------------------

CREATE OR REPLACE VIEW v_superstore_kpis AS
SELECT
    SUM(sales) AS total_sales,
    SUM(profit) AS total_profit,
    COUNT(DISTINCT order_id) AS total_orders,
    COUNT(DISTINCT customer_id) AS total_customers,
    SUM(profit)/NULLIF(SUM(sales),0) * 100 AS overall_profit_margin,
    AVG(discount) AS avg_discount,
    AVG(sales) AS avg_sales,
    AVG(profit) AS avg_profit
FROM v_superstore_base;


-----------------------------
-- Sales by Category
CREATE OR REPLACE VIEW v_sales_by_category AS
SELECT
    category,
    SUM(sales) AS total_sales,
    SUM(profit) AS total_profit
FROM v_superstore_base
GROUP BY category;

-- Sales by sub-category
CREATE OR REPLACE VIEW v_sales_by_subcategory AS
SELECT
    sub_category,
    SUM(sales) AS total_sales,
    SUM(profit) AS total_profit
FROM v_superstore_base
GROUP BY sub_category

-- Monthly Trend
CREATE OR REPLACE VIEW v_monthly_trend AS
SELECT
    EXTRACT(YEAR FROM order_date) AS year,
    EXTRACT(MONTH FROM order_date) AS month,
    SUM(sales) AS total_sales,
    SUM(profit) AS total_profit
FROM v_superstore_base
GROUP BY 1,2
ORDER BY 1,2;

--Customer Analysis
CREATE OR REPLACE VIEW v_customer_analysis AS
SELECT
    customer_id,
    customer_name,
    SUM(sales) AS lifetime_sales,
    SUM(profit) AS lifetime_profit,
    COUNT(DISTINCT order_id) AS total_orders,
    AVG(sales) AS avg_order_value
FROM v_superstore_base
GROUP BY customer_id, customer_name;





